name: bookmark_manager
description: A web app for managing bookmarks
# version: 1.0.0
# homepage: https://www.example.com
# author: Sebastian Kutschbach <sebastian.kutschbach@volkswagen.de>

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  angular: ^5.3.0
  angular_components: ^0.13.0
  http: ^0.12.0+4
  intl: ^0.15.0
  firebase: ^6.0.0

dev_dependencies:
  angular_test: ^2.3.0
  build_runner: ^1.5.0
  build_test: ^0.10.3
  build_web_compilers: ^2.1.0
  pedantic: ^1.7.0
  test: ^1.6.0
